---
#端口
server:
 port: 8022
spring:
  #给项目来个名字
  application:
    name: rabbitmq-consumer
  #配置rabbitMq 服务器
  rabbitmq:
    host: 47.97.211.150
    por: 5672
    username: root
    password: root
      #虚拟host 可以不设置,使用server默认host
    #virtual-host: JCcccHost